apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    app: todo
    component: redis
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


